version: '3.5'

services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker

    volumes:
      - ./:/var/www
    ports:
      - '9000:80'

    links:
      - app

  app:
    image:  mrcnzkk/php8.1_laravel_runner:latest
    #build:
    #  context: ./
    #  dockerfile: .docker/app.docker
    volumes:
      - ./:/var/www
    links:
      - db
      - cache

    environment:
      - 'REDIS_PORT=6379'
      - 'REDIS_HOST=cache'

  db:
      image: postgres:10.1
      environment:
          - POSTGRES_DB=${DB_DATABASE}
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
          - 5432:5432
      volumes:
          - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/

  cache:
    image: redis:4.0.6
    ports:
      - '6379:6379'
